service: aws4-axios

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.handler
    events:
      - http:
          method: ANY
          path: /ping
          authorizer: aws_iam
